Algoritmo "25/"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Erinaldo
// Descrição   : Lê uma variável e apresenta 25%
// Autor(a)    : Samira
// Data atual  : 07/08/2024
Var
// Seção de Declarações das variáveis 
   a: inteiro
   s: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreva ("Digite um número")
    leia (a)
    s<-a*0.25
    escreva ("25% de ",a," é igual a ", s)

Fimalgoritmo