Algoritmo "CNH"

Var
// Seção de Declarações das variáveis 
  idade: inteiro
  nome: caractere
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva ("Digite seu nome: ")
   leia (nome)
   escreva ("Digite sua idade: ")
   leia (idade)
   se (idade>=18) entao
   escreva ("Pode tirar CNH")
   senao
   escreva ("Não é possível tirar CNH")
   fimse

Fimalgoritmo