Algoritmo "igualmenormaior"

Var
// Seção de Declarações das variáveis 
  a,b: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva ("Digite o primeiro número: ")
  leia (a)
  escreva ("Digite o primeiro número: ")
  leia(b)
  se (a>b) entao
  escreva (a," é maior que ",b)
  fimse
  se (a<b) entao
  escreva (a," é menor que ",b)
  fimse
  se (a=b) entao
  escreva (a," é igual a ",b)
  fimse
   

Fimalgoritmo
