Algoritmo "teste"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Erinaldo
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Samira
// Data atual  : 07/08/2024
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       escreva ("Testando um algoritmo")

Fimalgoritmo