Algoritmo "triplo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Erinaldo
// Descrição   : Ler uma váriavel e apresentar seu triplo
// Autor(a)    : Samira
// Data atual  : 07/08/2024
Var
// Seção de Declarações das variáveis 
   a,s: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva ("Digite um número")
   leia(a)
   s<-a*3
   escreva ("O triplo de ",a," é igual a ", s)

Fimalgoritmo